# Primary Connection Settings
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/voting_system?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=0000

# Hibernate & JPA Logic
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true